### ISSUE TITLE
Proxy環境でgoogle変換ができない

### ISSUE THREAD

**Issue by yamam** [wachikun/yaskkserv2#29]
http/httpsにProxyが必要な環境でgoogle変換ができませんでした。
https://dtantsur.github.io/rust-openstack/reqwest/index.html
によるとHTTP_PROXY環境変数に設定されたProxyが使われるとのことでしたが、HTTP_PROXYを設定してもProxyは使われませんでした。
request.rsで以下のようにproxyを設定することでhttpでのgoogle変換ができることは確認しました。(原因不明ですがhttpsのproxyを設定してもhttpsでのgoogle変換はできませんでした)
```rs
    fn request(url: &str, timeout: u64) -> Result<String, SkkError> {
        let client = reqwest::Client::builder()
            .proxy(reqwest::Proxy::http("http://proxy-server:8080")?)
            .timeout(std::time::Duration::from_millis(timeout))
            .build()
```

proxyを設定するオプション追加の検討をお願いします。

**Comment by yamam** [comment]
環境を書き忘れました。
WSL2のUbuntu 22.04です。
opensslでビルドエラーが発生したため以下のサイトを参考に
https://arimasou16.com/blog/2022/04/29/00460/
以下をCargo.tomlに追加しました
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }

**Comment by wachikun** [comment]
ありがとうございます。
環境変数効かない件、こちらでも確認しました。
オプション追加自体は簡単ですが、 https の件もありますし、
ちょっと挙動が解せないので、しばらく時間をいただきたいです。

**Comment by yamam** [comment]
[f61eaf1](https://github.com/wachikun/yaskkserv2/commit/f61eaf1edcee31c14d3647d1b40680216169843b) で確認したところ環境変数の設定でgoogle 変換ができることを確認できましたのでクローズします。

**Comment by yamam** [comment]
またhttpsでもgoogle変換ができることを確認しました。(--google-use-httpを付けない)

**Comment by wachikun** [comment]
確認ありがとうございます。
セキュリティ対策で crate を最新にしたのが良かったみたいですね。
