### ISSUE TITLE
UTF-8の辞書の場合にUTF-8の見出しが変換されない

### ISSUE THREAD

**Issue by yamam** [wachikun/yaskkserv2#30]
UTF-8の辞書を使っていると変換結果はUTF-8で返るようになっていると思いますが、
クライアントから送信される見出しがEUC-JPになっている必要があるようでした。
クライアントから送信される見出しがUTF-8の場合にもUTF-8の変換結果を返してくれるようにしていただけないでしょうか？

見出しの文字コードについて他のSKK実装を調べましたが、以下のようになっていました。

cskkserv
クライアントの文字コードをUTF-8に設定すると
クライアントから送信されるUTF-8の見出しをUTF-8に変換する
https://github.com/nathancorvussolis/crvskkserv

SKKNET(SKK日本語入力FEPのSKKサーバ/クライアント)
文字コードをUTF-8に指定した場合にskkservに送信される見出しの文字コードはUTF-8
http://coexe.web.fc2.com/skknet.html

uim-skkのUTF-8化のパッチ
skkservに送信される見出しの文字コードはUTF-8
https://keens.github.io/blog/2019/10/20/patchiwoateteuim_skkwoutf_8kasuru/

**Comment by wachikun** [comment]
調査ありがとうございます!
uim-skk は utf-8 で使用していないので気付きませんでした……。
とりあえず、見出しを utf8 として受け付ける --midashi-utf8 オプションを追加した feature/midashi-utf8-20220520_a branch を push してみました。
しばらく使ってみて問題がないようなら、あとで master に merge しますね。

**Comment by yamam** [comment]
対応ありがとうございます。
UTF-8パッチをあてたuim-skkで変換できることを確認しました。
